/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ScoreRecord = IDL.Record({
  'score' : IDL.Nat,
  'headshots' : IDL.Nat,
});
export const PlayerSettings = IDL.Record({
  'audioVolume' : IDL.Float64,
  'sensitivity' : IDL.Float64,
  'aimAssistEnabled' : IDL.Bool,
  'qualitySettings' : IDL.Text,
});
export const PlayerProfile = IDL.Record({
  'bestScore' : ScoreRecord,
  'settings' : PlayerSettings,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllPlayerProfiles' : IDL.Func([], [IDL.Vec(PlayerProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPlayerProfile' : IDL.Func([], [PlayerProfile], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'savePlayerSettings' : IDL.Func([PlayerSettings], [], []),
  'updateBestScore' : IDL.Func([ScoreRecord], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ScoreRecord = IDL.Record({ 'score' : IDL.Nat, 'headshots' : IDL.Nat });
  const PlayerSettings = IDL.Record({
    'audioVolume' : IDL.Float64,
    'sensitivity' : IDL.Float64,
    'aimAssistEnabled' : IDL.Bool,
    'qualitySettings' : IDL.Text,
  });
  const PlayerProfile = IDL.Record({
    'bestScore' : ScoreRecord,
    'settings' : PlayerSettings,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllPlayerProfiles' : IDL.Func([], [IDL.Vec(PlayerProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPlayerProfile' : IDL.Func([], [PlayerProfile], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'savePlayerSettings' : IDL.Func([PlayerSettings], [], []),
    'updateBestScore' : IDL.Func([ScoreRecord], [], []),
  });
};

export const init = ({ IDL }) => { return []; };